-- NOTA: Este archivo ya no se usa directamente
--
-- El sistema ahora usa SQLite en lugar de MySQL
-- La base de datos se inicializa automáticamente usando el script install.sh
--
-- Para crear manualmente la base de datos, ejecuta:
--   php backend/init_database.php [usuario] [contraseña]
--
-- Ejemplo:
--   php backend/init_database.php admin micontraseña
